/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface SkBox {
    'boxtitle': string;
    'description': string;
  }
  interface SkBoxAttributes extends StencilHTMLAttributes {
    'boxtitle'?: string;
    'description'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'SkBox': Components.SkBox;
  }

  interface StencilIntrinsicElements {
    'sk-box': Components.SkBoxAttributes;
  }


  interface HTMLSkBoxElement extends Components.SkBox, HTMLStencilElement {}
  var HTMLSkBoxElement: {
    prototype: HTMLSkBoxElement;
    new (): HTMLSkBoxElement;
  };

  interface HTMLElementTagNameMap {
    'sk-box': HTMLSkBoxElement
  }

  interface ElementTagNameMap {
    'sk-box': HTMLSkBoxElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
